spring:
  application:
    # This ends up as the service name in zipkin
    name: sleuth-zipkin
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    # Assuming that zipkinserver is the service name of zipkin server.
    baseUrl: http://zipkinserver

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
